### ISSUE TITLE
Sliders don't work anymore if you set them at max

### ISSUE THREAD

**Issue by marcorivm** [ewgenius/paper-interval-slider#5]
In the interval slider , after i have setted the knobs at the max, and i try to slide them again, it does not work anymore, could you fix this? please. Thanks in advance.

**Comment by ewgenius** [comment]
Are you realy need this working in 0.5 Polymer version? Because of upcoming 1.0 release, i think it is not necessary to support this old version, and i'm going to rewrite this component, after release.

**Comment by marcorivm** [comment]
Being honest i don't use polymer, but your component is pretty good, this component looks like material design, however for a strange reason it's not in material design. Well, i am working in an Angular app then i adapted your component to work for angular, for me no matter which polymer version is.
